import { createStoryReporter } from 'executable-stories-vitest/reporter';
import { defineConfig } from 'vitest/config';

/**
 * Story tests double as the package's living documentation: the same run that
 * proves the analysis logic works emits the markdown describing what it does.
 * That is the point of writing them as stories rather than as bare asserts —
 * the behaviour spec cannot drift from the code, because it is generated by it.
 */
export default defineConfig({
  test: {
    environment: 'node',
    include: ['src/**/*.test.ts'],
    exclude: ['dist/**', 'node_modules/**'],
    coverage: {
      provider: 'v8',
      include: ['src/**/*.ts'],
      // Re-export barrels and entry points: the entry points are exercised by
      // spawning the built binary, which in-process coverage cannot see.
      exclude: ['src/**/*.test.ts', 'src/{index,testing,advanced,test-support}.ts'],
      reporter: ['text-summary', 'html'],
      thresholds: { lines: 95, statements: 95, functions: 90, branches: 85 },
    },
    reporters: [
      'default',
      createStoryReporter({
        formats: ['markdown'],
        outputDir: 'docs',
        outputName: 'stories',
        output: { mode: 'aggregated' },
        markdown: {
          title: 'testrail-ai — behaviour',
          includeMetadata: false,
          includeStatusIcons: true,
          stepStyle: 'bullets',
          sortScenarios: 'source',
        },
      }),
      // reports/test-results.{html,md}: what the executable-stories action posts on a PR.
      createStoryReporter({
        formats: ['html', 'markdown'],
        outputDir: 'reports',
        outputName: 'test-results',
        html: { title: 'testrail-ai' },
      }),
    ],
  },
});
